packages:
  - '.'
  - '../security'
  - 'examples/sveltekit-quickstart'

blockExoticSubdeps: true
engineStrict: true
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
allowBuilds:
  esbuild: true

overrides:
  '@sveltejs/kit': 2.70.3
  cookie: 0.7.2
  esbuild: 0.28.1
  immutable: ^4.3.9
  nanoid: 3.3.18
  postcss: 8.5.26
  vite: 8.2.2
